Traceback (most recent call last):
  File "/tmp/tmpo99xttzv", line 94, in <module>
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '194.txt'