Traceback (most recent call last):
  File "/tmp/tmp0uxcvpxv", line 49, in <module>
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data.txt'